services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    expose:
      - "8000"
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        VITE_API_BASE_URL: https://desafio-alexsandre.duckdns.org/api
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_certs:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"

volumes:
  certbot_certs:
  certbot_www: