# Generated by Django 6.1.1 on 2026-09-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='numero_nota_fiscal',
        ),
    ]
